leffavuokraamo/urls.py
from django.urls import path
from . import views
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views

admin.site.site_url='/leffavuokraamo'

app_name = 'leffavuokraamo'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('user/', views.user_page, name="user"),
    path('movies', views.movies, name="movies"),
    path('login_page/', views.login_page, name="login"),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('edit_profile/', views.edit_profile, name="edit_profile"),
    path('movies/<pk>/', views.MovieDetailsView.as_view(), name="moviedetails"),
    path('rent/<int:film_id>', views.rent_movie, name="rent_movie"),
    path('return/<int:rental_id>', views.return_movie, name="return_movie"),
    path('registeration/', views.registeration_page, name="registeration")
    
]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    
    path('leffavuokraamo/', include('leffavuokraamo.urls')),
    path('admin/', admin.site.urls),
    path('leffavuokraamo/', include('django.contrib.auth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leffavuokraamo/models.py
from datetime import timedelta, date
from django.db import models
from django.contrib.auth.models import User


class Director(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Tag(models.Model):
    tag = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.tag}"
    # Indeksointi, nopeuttaa hakutoimintoja
    class Meta:
        indexes = [
            models.Index(fields=['tag'])
        ]


class Genre(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.name}"
    # Indeksointi, nopeuttaa hakutoimintoja
    class Meta:
        indexes = [
            models.Index(fields=['name'])
        ]


class Film(models.Model):
    title = models.CharField('Elokuvan nimi',max_length=50)
    description = models.TextField(max_length=2000)
    release_date = models.DateField('Julkaisupäivä')
    language = models.CharField('Puhuttu kieli',max_length=50)
    is_loaned = models.BooleanField('On vuokrattuna',default=False)
    image = models.ImageField(upload_to='images/')
    directors = models.ManyToManyField(Director) # FOREIGN KEY, suhde moni-moni
    genres = models.ManyToManyField(Genre) # FOREIGN KEY, suhde moni-moni
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return f"{self.title}"
    # Indeksointi, nopeuttaa hakutoimintoja
    class Meta:
        indexes = [
            models.Index(fields=['title'])
        ]
        

class Rental(models.Model):
    # funktio palautuspäivälle, eli lisää nykyiseen päivään 14 päivää
    def return_date_time():
        now = date.today()
        return now + timedelta(days=14)

    customer = models.ForeignKey(User, on_delete = models.CASCADE) # Jos asiakas poistetaan, vuokraus jää silti teitokantaan ja asiakas nulliksi
    film = models.ForeignKey(Film, null=True, on_delete = models.SET_NULL)
    rental_date = models.DateField('Päivä jolloin vuokrattu',auto_now_add = True) # Luodaan automaattisesti, kun vuokraus luodaan ensimmäistä kertaa
    last_return_date = models.DateField('Viimeinen palautuspäivä',default=return_date_time) 
    date_returned = models.DateField('Päivä jolloin palautettu',null=True)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return f"Vuokraaja: {self.customer} - Päiväys: {self.rental_date}"

leffavuokraamo/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django import forms
from django.http import HttpResponse




class CreateUserForm(UserCreationForm):
    first_name = forms.CharField(label='Etunimi') 
    last_name = forms.CharField(label='Sukunimi') 
    username = forms.CharField(label='Käyttäjätunnus')  
    email = forms.EmailField(label='Sähköposti')  
    password1 = forms.CharField(label='Salasana', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Vahvista salasana', widget=forms.PasswordInput)  

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']
        


class CreateEditForm(UserChangeForm):
    password = None
    email = forms.EmailField(label='Sähköposti')
    first_name = forms.CharField(label='Etunimi') 
    last_name = forms.CharField(label='Sukunimi') 
    username = forms.CharField(label='Käyttäjätunnus')  
     
    
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name' ]
        

leffavuokraamo/views.py
from datetime import date
from django.db.models import Q
from django.shortcuts import redirect, render 
from django.views import generic
from .models import Film, Rental, Genre, Tag
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import CreateUserForm, CreateEditForm


def index(request):
    print(request.headers)
    return render(request, "leffavuokraamo/index.html",{})


@login_required(login_url='/leffavuokraamo/login_page')
def user_page(request):
    user = request.user
    rentals = Rental.objects.filter(customer=user).order_by('-rental_date')
    context = {"user": user, "rentals": rentals}
    return render(request, "leffavuokraamo/user_page.html", context)


def return_movie(request, rental_id):
    rental = Rental.objects.get(id=rental_id)
    return_date = date.today()
    setattr(rental, 'is_active', 'False')
    setattr(rental, 'date_returned', return_date)
    film = getattr(rental, 'film')
    setattr(film, 'is_loaned', 'False')
    film.save()
    rental.save()
    return render(request, "leffavuokraamo/return_success.html", {'film': film})


def movies(request):
    all_films = Film.objects.all().order_by('title')
    context = {"all_films":all_films}
    word = ''
    results = []
    if 'word' in request.GET:
        word = request.GET['word']
        if len(word)>0:
            genres = Genre.objects.filter(name__icontains=word)
            tags = Tag.objects.filter(tag__icontains=word)
            results = Film.objects.filter(Q(title__icontains=word) | Q(genres__in=genres) | Q(tags__in=tags))
        context = {'results': results}
    return render(request, 'leffavuokraamo/movies_page.html', context)


class MovieDetailsView(generic.DetailView):
    model = Film
    template_name = 'leffavuokraamo/moviedetails_page.html'


@login_required(login_url='/leffavuokraamo/login_page')
def rent_movie(request, film_id):
    film = Film.objects.get(id=film_id)
    setattr(film, 'is_loaned', 'True')
    film.save()
    customer = request.user
    rental = Rental(film=film, customer=customer)
    setattr(rental, 'is_active', 'True')
    rental.save()
    context = {"film": film, "customer": customer, "rental": rental}
    return render(request, 'leffavuokraamo/movierent_page.html', context)


def success(request):
    return render(request, 'leffavuokraamo/movierent_page.html',{})


# REKISTERÖITYMISSIVU
 
def registeration_page(request):
    form = CreateUserForm()
    
    if request.method =="POST":
        form = CreateUserForm(request.POST)
        
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, "Käyttäjätunnus luotu käyttäjälle " + user)
            return redirect('leffavuokraamo:login')
    context = {'form':form }
    
    return render(request, 'leffavuokraamo/registeration_page.html', context)

     
# KIRJAUTUMISSIVU
   
def login_page(request):
    if request.method == "POST":
        username = request.POST['käyttäjätunnus']
        password = request.POST['salasana']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('leffavuokraamo:user')
        else:
            messages.success(request, ("Virheellinen käyttäjätunnus tai salasana. Yritä uudelleen."))
            return redirect('leffavuokraamo:login')
    
    else:
    
       return render(request, "leffavuokraamo/login_page.html",{})


# MUOKKAA PROFIILIA

def edit_profile(request):
    form = CreateEditForm()
    
    if request.method =="POST":
        form = CreateEditForm(request.POST, instance=request.user)
        
        if form.is_valid():
            form.save()
            
            messages.success(request, ("Käyttäjätietoja muokattu"))
            return redirect('leffavuokraamo:user')
            
            
    else:
        form = CreateEditForm(instance=request.user)
        context = {'form': form}
        return render(request, 'leffavuokraamo/edit_profile.html', context)

    context = {'form': form}
    return render(request, 'leffavuokraamo/edit_profile.html', context)

leffavuokraamo/templates/leffavuokraamo/edit_profile.html
{% extends "leffavuokraamo/base.html" %}

{% block navibar%}

{% if user.is_authenticated %}
<a href="{% url 'leffavuokraamo:index' %}">Etusivu</a>
<a href="{% url 'leffavuokraamo:movies' %}">Leffat</a>
<a class="active" href="{% url 'leffavuokraamo:user' %}">Omat sivut</a>
{% comment %} <a href="{% url 'leffavuokraamo:login' %}">Kirjaudu</a> {% endcomment %}
<a href="{% url 'leffavuokraamo:logout' %}">Kirjaudu ulos</a>
    {% else %}
    <a href="{% url 'leffavuokraamo:index' %}">Etusivu</a>
    <a href="{% url 'leffavuokraamo:movies' %}">Leffat</a>
    <a class="active" href="{% url 'leffavuokraamo:user' %}">Omat sivut</a>
    <a href="{% url 'leffavuokraamo:login' %}">Kirjaudu</a>
    <a href="{% url 'leffavuokraamo:registeration' %}">Rekisteröidy</a>
{% endif %}
{% endblock %}

{% block content %}

<h1 class="h1_style">Muokkaa profiilia</h1>
<br/><br/>

<form method="post">
        {% csrf_token %}

            <div class="cont">
                {{form.as_p}}
            
                <br></br>
            </div>
    
  
    <button type="submit">Päivitä tiedot</button>

    


</form>

    

{% endblock %}



 

leffavuokraamo/templates/leffavuokraamo/index.html
<!-- PÄÄSIVU -->
<!DOCTYPE html>

<html lang = "fi">



<head>
    <meta charset="UTF-8">
    <title>Lainakooderien elokuvavuokraamo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Lainakooderien elokuvavuokraamo">
    <meta name="keywords" content="elokuva,leffa,vuokra,leffailta,elokuvailta">
    <meta name="author" content="Lainakooderit - INTIM21A6">
    {% load static %}
    <link rel="stylesheet" href="{% static 'leffavuokraamo/style.css'%}">
</head>





<body>

    <!-- Otsikkokuva (HEADER) -->
    <div class="otsikkoalue">{% block header %}
        <img src="{% static 'leffavuokraamo/header_1.jpg' %}" alt="Leffavuokraamo" class="otsikkokuva">
        <img src="{% static 'leffavuokraamo/header_2.jpg' %}" alt="Leffavuokraamo" class="otsikkokuvapieni">
        {% endblock %}
    </div>

    <!-- NAVIGOINTIPALKKI -->
    <nav class="navigoi">{% block navibar %}
        
        {% if user.is_authenticated %}
        <a class="active" href= "{% url 'leffavuokraamo:index' %}">Etusivu</a>
        <a href="{% url 'leffavuokraamo:movies' %}">Leffat</a>
        <a href="{% url 'leffavuokraamo:user' %}">Omat sivut</a>
        {% comment %} <a href="{% url 'leffavuokraamo:login' %}">Kirjaudu</a> {% endcomment %}
        <a href="{% url 'leffavuokraamo:logout' %}">Kirjaudu ulos</a>
            {% else %}
            <a class="active" href= "{% url 'leffavuokraamo:index' %}">Etusivu</a>
            <a href="{% url 'leffavuokraamo:movies' %}">Leffat</a>
            <a href="{% url 'leffavuokraamo:user' %}">Omat sivut</a>
            <a href="{% url 'leffavuokraamo:login' %}">Kirjaudu</a>
            <a href="{% url 'leffavuokraamo:registeration' %}">Rekisteröidy</a>

        {% endif %}
        {% endblock %}
    </nav>




    <!-- Sisältöalue-->
    <div class= "sisältöalue">{% block content %}
        <h1 class="h1_style">Tervetuloa elokuvien vuokrauspalveluun</h1>
        {% endblock %}
    </div>


    <!-- Slideshow container -->
        <div class="slideshow-container">{% block slideshow %}

            <!-- Full-width images with number and caption text -->
            <div class="mySlides fade">
            <div class="numbertext">1 / 6</div>
            <a href="/leffavuokraamo/movies/14">
            <img src="/media/images/60seconds.jpg" style="width:100%"></a>
            </div>
        
            <div class="mySlides fade">
            <div class="numbertext">2 / 6</div>
            <a href="/leffavuokraamo/movies/5">
            <img src="/media/images/ghostprotocol.jpg" style="width:100%"></a>
            </div>
        
            <div class="mySlides fade">
            <div class="numbertext">3 / 6</div>
            <a href="/leffavuokraamo/movies/6">
            <img src="/media/images/forceawakens.jpg" style="width:100%"></a>
            </div>

            <div class="mySlides fade">
            <div class="numbertext">4 / 6</div>
            <a href="/leffavuokraamo/movies/21">
            <img src="/media/images/Napapiirin_Sankarit.jpg" style="width:100%"></a>
            </div>

            <div class="mySlides fade">
                <div class="numbertext">5 / 6</div>
                <a href="/leffavuokraamo/movies/18">
                <img src="/media/images/revenge.jpg" style="width:100%"></a>
            </div>

            <div class="mySlides fade">
                <div class="numbertext">6 / 6</div>
                <a href="/leffavuokraamo/movies/12">
                <img src="/media/images/lohikaarme.jpg" style="width:100%"></a>
            </div>
                
        
            <!-- Next and previous buttons -->
            <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
            <a class="next" onclick="plusSlides(1)">&#10095;</a>
        </div>
        <br>
        
        <!-- The dots/circles -->
        <div style="text-align:center">
            <span class="dot" onclick="currentSlide(1)"></span>
            <span class="dot" onclick="currentSlide(2)"></span>
            <span class="dot" onclick="currentSlide(3)"></span>
            <span class="dot" onclick="currentSlide(4)"></span>
            <span class="dot" onclick="currentSlide(5)"></span>
            <span class="dot" onclick="currentSlide(6)"></span>
        </div>
          {% endblock %}  
    </div>

    <script>
        let slideIndex = 0;
        showSlides();
        
        function showSlides() {
          let i;
          let slides = document.getElementsByClassName("mySlides");
          let dots = document.getElementsByClassName("dot");
          for (i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";  
          }
          slideIndex++;
          if (slideIndex > slides.length) {slideIndex = 1}    
          for (i = 0; i < dots.length; i++) {
            dots[i].className = dots[i].className.replace(" active", "");
          }
          slides[slideIndex-1].style.display = "block";  
          dots[slideIndex-1].className += " active";
          setTimeout(showSlides, 3000); // Change image every 3 seconds
        }
        </script>

    <div class ="allekirjoitus">
        <p class ="allekirjoitusteksti">Harjoitustyö Web-ohjelmointi - Lainakooderit / INTIM21A6 /{% block adminsite %}<a href="admin/"> 2022</a>{% endblock %}</p>
    </div>




</body>


</html>

leffavuokraamo/templates/leffavuokraamo/login_page.html
{% extends "leffavuokraamo/base.html" %}


{% block content %}

{% if user.is_authenticated %}
    <h2 class="h1_style">Käyttäjä kirjautunut: {{ user }}</h2>
    <h2 class="h1_style"><a href="{% url 'logout' %}">Kirjaudu ulos</a></h2>
{% else %}
    <h1 class="h1_style">Kirjaudu sisään</h1>
    <h2 class="h1_style">Sinun täytyy ensin kirjautua sisään, jotta voit vuokrata elokuvia</h2>
    <div class="cont">
        {% if messages %}
            {% for message in messages %}
            
                {{ message }}
                
            {% endfor %}
        {% endif %}
    </div>
    
    <form method="post">
        {% csrf_token %}
        
        
            
            
            <div class="cont">
              <label for="exampleInputEmail1" class="form-label">Käyttäjätunnus: </label>
              <input type="text" class="form-control" name="käyttäjätunnus" aria-describedby="emailHelp">
             
            </div>
            <div class="cont">
              <label for="exampleInputPassword1" class="form-label">Salasana: </label>
              <input type="password" class="form-control" name="salasana">
            </div>
            
        
        <button class="painike">Kirjaudu sisään</button>
    </form>
    
    <h2 class="h1_style">Jos sinulla ei ole vielä käyttäjätunnusta, <a href="{% url 'leffavuokraamo:registeration' %}">luo uusi käyttäjä</a></h2>
{% endif %}


{% endblock %}



{% block navibar %}

{% if user.is_authenticated %}
<a href="{% url 'leffavuokraamo:index' %}">Etusivu</a>
<a href="{% url 'leffavuokraamo:movies' %}">Leffat</a>
<a href="{% url 'leffavuokraamo:user' %}">Omat sivut</a>
{% comment %} <a class="active" href="{% url 'leffavuokraamo:login' %}">Kirjaudu</a> {% endcomment %}
<a href="{% url 'leffavuokraamo:logout' %}">Kirjaudu ulos</a>

    {% else %}
        <a href="{% url 'leffavuokraamo:index' %}">Etusivu</a>
        <a href="{% url 'leffavuokraamo:movies' %}">Leffat</a>
        <a href="{% url 'leffavuokraamo:user' %}">Omat sivut</a>
        <a class="active" href="{% url 'leffavuokraamo:login' %}">Kirjaudu</a>
        <a href="{% url 'leffavuokraamo:registeration' %}">Rekisteröidy</a>
{% endif %}
{% endblock %}


{% block slideshow %}
{% endblock %}

{% block adminsite %}
<p class = "allekirjoitusteksti">2022</p>
{% endblock %}

leffavuokraamo/templates/leffavuokraamo/moviedetails_page.html
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>
{% extends "leffavuokraamo/base.html" %}
{% block navibar %}

{% if user.is_authenticated %}
<a href="{% url 'leffavuokraamo:index' %}">Etusivu</a>
<a class="active" href="{% url 'leffavuokraamo:movies' %}">Leffat</a>
<a href="{% url 'leffavuokraamo:user' %}">Omat sivut</a>
<a href="{% url 'leffavuokraamo:logout' %}">Kirjaudu ulos</a>
    {% else %}
    <a href="{% url 'leffavuokraamo:index' %}">Etusivu</a>
    <a class="active" href="{% url 'leffavuokraamo:movies' %}">Leffat</a>
    <a href="{% url 'leffavuokraamo:user' %}">Omat sivut</a>
    <a href="{% url 'leffavuokraamo:login' %}">Kirjaudu</a>
    <a href="{% url 'leffavuokraamo:registeration' %}">Rekisteröidy</a>
{% endif %}
{% endblock %}
{% block content %}
<h1 class="h1_style" style="font-weight:bolder; margin-top:20px">{{ object.title }}</h1>
<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <h2>Kuvaus</h2>
            <p>{{ object.description }}</p>
        </div>
        <div class="col-sm-4" style="padding-left:10%">
            <h2>Tiedot</h2>
            <p>Julkaistu: {{ object.release_date.year }}</p>
            <p>Kieli: {{ object.language }}</p>
            <p>Ohjaajat:
                <ul>
                    {% for director in object.directors.all %}
                    <li>{{ director.first_name }} {{ director.last_name }}</li>
                    {% endfor %}
                </ul>
            </p>
            <p>Genret:
                <ul>
                    {% for genre in object.genres.all %}
                    <li>{{ genre.name }}</li>
                    {% endfor %}
                </ul>
            </p>
            <p>Tagit:
                <ul>
                    {% for tag in object.tags.all %}
                    <li>{{ tag.tag }}</li>
                    {% endfor %}
                </ul>
            </p>
            {% if film.is_loaned == False %}
            <p><a href="{% url 'leffavuokraamo:rent_movie' film.id %}">Vuokraa elokuva</a></p>
            {% else %}
            <br><p class="punainen">Elokuva on juuri nyt vuokrattuna.<p>
            {% endif %}
        </div>
        <div class="col-sm-4">
            <img alt="Elokuvan {{ object.title }} posteri" src="{{ object.image.url }}" style="max-width: 90%"/>
        </div>
    </div>
</div>
{% endblock %}
{% block adminsite %}
<p class = "allekirjoitusteksti">2022</p>
{% endblock %}

leffavuokraamo/templates/leffavuokraamo/movierent_page.html
{% extends "leffavuokraamo/base.html" %}
{% block navibar %}
{% if user.is_authenticated %}
<a href="{% url 'leffavuokraamo:index' %}">Etusivu</a>
<a class="active" href="{% url 'leffavuokraamo:movies' %}">Leffat</a>
<a href="{% url 'leffavuokraamo:user' %}">Omat sivut</a>
<a href="{% url 'leffavuokraamo:logout' %}">Kirjaudu ulos</a>
    {% else %}
    <a href="{% url 'leffavuokraamo:index' %}">Etusivu</a>
    <a class="active" href="{% url 'leffavuokraamo:movies' %}">Leffat</a>
    <a href="{% url 'leffavuokraamo:user' %}">Omat sivut</a>
    <a href="{% url 'leffavuokraamo:login' %}">Kirjaudu</a>
    <a href="{% url 'leffavuokraamo:registeration' %}">Rekisteröidy</a>
{% endif %}
{% endblock %}
{% block content %}
<h1 class="h1_style">Elokuvan {{ film.title }} vuokraus onnistui</h1>
<div class="listaus">
    <h2>Vuokrauksen tiedot:</h2>
    <p>Vuokraaja: {{ customer }}</p>
    <p>Elokuva: {{ film.title }}</p>
    <p>Vuokrauspäivä: {{ rental.rental_date|date:"j.n.Y" }}</p>
    <p>Viimeinen palautuspäivä: {{ rental.last_return_date|date:"j.n.Y" }}</p>
</div>
{% endblock %}

leffavuokraamo/templates/leffavuokraamo/registeration_page.html
{% extends "leffavuokraamo/base.html" %}


  

 {% block content %}
 <h1 class="h1_style">Rekisteröityminen</h1>
 

<form method="POST" novalidate>
    {% csrf_token %}
    
    <div class="cont">
        {{form.as_p}}
    </div>
   
    
    
  
  
  <button type="submit">Luo käyttäjätunnus</button>

</form>
 
{% endblock %}









 

  

{% block navibar %}

{% if user.is_authenticated %}
<a href="{% url 'leffavuokraamo:index' %}">Etusivu</a>
<a href="{% url 'leffavuokraamo:movies' %}">Leffat</a>
<a href="{% url 'leffavuokraamo:user' %}">Omat sivut</a>
<a href="{% url 'leffavuokraamo:logout' %}">Kirjaudu ulos</a>
  {% else %}
  <a href="{% url 'leffavuokraamo:index' %}">Etusivu</a>
  <a href="{% url 'leffavuokraamo:movies' %}">Leffat</a>
  <a href="{% url 'leffavuokraamo:user' %}">Omat sivut</a>
  <a href="{% url 'leffavuokraamo:login' %}">Kirjaudu</a>
  <a class="active" href="{% url 'leffavuokraamo:registeration' %}">Rekisteröidy</a>
{% endif %}
{% endblock %}

{% block slideshow %}
{% endblock %}

{% block adminsite %}
<p class = "allekirjoitusteksti">2022</p>
{% endblock %}

leffavuokraamo/templates/leffavuokraamo/user_page.html
{% extends "leffavuokraamo/base.html" %}

{% block navibar%}

{% if user.is_authenticated %}
<a href="{% url 'leffavuokraamo:index' %}">Etusivu</a>
<a href="{% url 'leffavuokraamo:movies' %}">Leffat</a>
<a class="active" href="{% url 'leffavuokraamo:user' %}">Omat sivut</a>
{% comment %} <a href="{% url 'leffavuokraamo:login' %}">Kirjaudu</a> {% endcomment %}
<a href="{% url 'leffavuokraamo:logout' %}">Kirjaudu ulos</a>
    {% else %}
    <a href="{% url 'leffavuokraamo:index' %}">Etusivu</a>
    <a href="{% url 'leffavuokraamo:movies' %}">Leffat</a>
    <a class="active" href="{% url 'leffavuokraamo:user' %}">Omat sivut</a>
    <a href="{% url 'leffavuokraamo:login' %}">Kirjaudu</a>
    <a href="{% url 'leffavuokraamo:registeration' %}">Rekisteröidy</a>
{% endif %}
{% endblock %}

{% block content %}
<h1 class="h1_style">Käyttäjän {{ user }} omat sivut</h1>
{% if user.is_authenticated %}
<h2 class="h1_style"><a href="{% url 'leffavuokraamo:edit_profile' %}">Muokkaa omia tietoja</a></h2>
    {% for message in messages%}
        {{ message }}
    {% endfor %}
{% endif %}
<div class="listaus">
    {% if rentals %}
    <br><h2>Vuokratut elokuvat:</h2><br>
    {% for rental in rentals%}
    <h3>{{ rental.film }}</h3>
    <p>Vuokrauspäivä: {{ rental.rental_date|date:"j.n.Y" }}</p>
    <p>Viimeinen palautuspäivä: {{ rental.last_return_date|date:"j.n.Y" }}</p>
    {% if rental.is_active == True %}
    <p>Tila: VUOKRATTU</p>
    <p><p><a href="{% url 'leffavuokraamo:return_movie' rental.id %}">Palauta elokuva</a></p>
    {% else %}
    <p>Tila: PALAUTETTU {{ rental.date_returned|date:"j.n.Y" }}</p>
    {% endif %}
    <br><br>
    {% endfor %}
    {% else %}
    <p>Sinulla ei ole vuokrattuja elokuvia.</p>
</div>
{% endif %}
{% endblock %}

{% block adminsite %}
<p class = "allekirjoitusteksti">2022</p>
{% endblock %}